"""Configuration file for nmea-mqtt-py

    DO NOT EDIT THIS FILE!

Instead, copy it to config.py, then edit the copy.
     cp config-sample.py config.py
     nano config.py
"""

# Set to 1 for debug messages, set to 2 for even more messages
DEBUG = 0

# Vessel related
MMSI = 368323170

# NMEA socket connection.  NMEA_SOCKETS is a list of 3-way tuples (channel, ip, port), where
# channel is a string.
NMEA_SOCKETS = [
    ("ch1", "localhost", 10110),
    ("ch2", "localhost", 10111),
]
NMEA_TIMEOUT = 20
NMEA_RETRY_WAIT = 60

# MQTT configuration.
MQTT_BROKER = "localhost"
MQTT_PORT = 1883
MQTT_TOPIC_PREFIX = "nmea"
MQTT_USERNAME = ""
MQTT_PASSWORD = ""

# How often to publish in milliseconds. If a sentence is not listed below, it will not get published.
PUBLISH_INTERVALS = {
    "DPT": 10000,
    "GGA": 10000,
    "GLL": 10000,
    "HDT": 10000,
    "MDA": 10000,
    "MWV": 10000,
    "RMC": 10000,
    "ROT": 10000,
    "RSA": 10000,
    "VTG": 10000,
    "VWR": 10000,
}
